spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth_route
          uri: http://localhost:8081  # ?? ??? ???
          predicates:
            - Path=/auth/**
        - id: chat_route
          uri: http://localhost:8082  # ?? ??? ???
          predicates:
            - Path=/api/chat/**
          filters:
            - CustomLoggingFilter
logging:
  level:
    org.springframework.cloud.gateway: TRACE